/*  Machine generated symbol file "esentprf.hxx" from "perfdata.txt" */


#define ESE 0
#define PagesConvertedSec 2
#define PagesConvertedTotal 4
#define RecordsConvertedSec 6
#define RecordsConvertedTotal 8
#define OSHeapAllocPerSec 10
#define OSHeapFreePerSec 12
#define OSHeapAlloc 14
#define OSHeapBytesAlloc 16
#define OSPageBytesReserved 18
#define OSPageBytesCommitted 20
#define FCBAsyncScan 22
#define FCBAsyncPurge 24
#define FCBAsyncThresholdScan 26
#define FCBAsyncThresholdPurge 28
#define FCBAsyncPurgeConflict 30
#define FCBSyncPurge 32
#define FCBSyncPurgeStalls 34
#define FCBAllocWaitForVersionCleanup 36
#define FCBCacheHits 38
#define FCBCacheRequests 40
#define FCBCacheStalls 42
#define FCBCacheMax 44
#define FCBCachePreferred 46
#define FCBCacheAlloc 48
#define FCBCacheAllocAvail 50
#define PIBInUse 52
#define PIBUsed 54
#define PIBTotal 56
#define TableOpenCacheHitRate 58
#define TableOpenCacheRequests 60
#define TableOpenCacheHitsPerSec 62
#define TableOpenCacheMissesPerSec 64
#define TableOpensPerSec 66
#define LGBytesWrittenPerSec 68
#define LGUsersWaiting 70
#define UserROTrxCommit0PerSec 72
#define UserRWTrxCommit0PerSec 74
#define UserTrxCommit0PerSec 76
#define UserROTrxRollback0PerSec 78
#define UserRWTrxRollback0PerSec 80
#define UserTrxRollback0PerSec 82
#define SystemROTrxCommit0PerSec 84
#define SystemRWTrxCommit0PerSec 86
#define SystemTrxCommit0PerSec 88
#define SystemROTrxRollback0PerSec 90
#define SystemRWTrxRollback0PerSec 92
#define SystemTrxRollback0PerSec 94
#define IODatabaseFileExtensionStall 96
#define LGRecordPerSec 98
#define LGCapacityFlushPerSec 100
#define LGCommitFlushPerSec 102
#define LGFlushPerSec 104
#define LGWritePerSec 106
#define LGStallPerSec 108
#define VERcbucketAllocated 110
#define VERcbucketDeleteAllocated 112
#define VERBucketAllocWaitForVersionCleanup 114
#define VERcbAverageBookmark 116
#define VERUnnecessaryCalls 118
#define VERAsyncCleanupTasksDispatched 120
#define VERSyncCleanupTasksDispatched 122
#define VERCleanupTasksDiscarded 124
#define VERCleanupTasksFailed 126
#define BTAppendSplit 128
#define BTRightSplit 130
#define BTVerticalSplit 132
#define BTSplit 134
#define BTEmptyPageMerge 136
#define BTRightMerge 138
#define BTPartialMerge 140
#define BTMerge 142
#define BTSeekShortCircuit 144
#define BTUnnecessarySiblingLatch 146
#define BTNext 148
#define BTPrev 150
#define BTSeek 152
#define BTInsert 154
#define BTReplace 156
#define BTFlagDelete 158
#define BTDelete 160
#define BTAppend 162
#define SPCreate 164
#define SPCreateCum 166
#define SPDelete 168
#define SPDeleteCum 170
#define BFCacheHits 172
#define BFCacheRequests 174
#define BFPctClean 176
#define BFTotalBuffers2 178
#define BFPagesReadPerSec 180
#define BFPagesWrittenPerSec 182
#define BFPagesTransferredPerSec 184
#define BFLatch 186
#define BFFastLatch 188
#define BFBadLatchHint 190
#define BFPctFastLatch 192
#define BFTotalLatches 194
#define BFLatchConflict 196
#define BFLatchStall 198
#define BFPctAvail 200
#define BFTotalBuffers3 202
#define BFCacheFault 204
#define BFCacheEvict 206
#define BFAvailStallsPerSec 208
#define BFCacheSize 210
#define BFPctStartFlushThreshold 212
#define BFTotalBuffers4 214
#define BFPctStopFlushThreshold 216
#define BFTotalBuffers5 218
#define BFPagesPreread 220
#define BFCachedPagesPreread 222
#define BFPagesPrereadUntouched 224
#define BFPagesVersioned 226
#define BFPctVersioned 228
#define BFTotalBuffers6 230
#define BFPagesOrdinarilyWritten 232
#define BFPagesAnomalouslyWritten 234
#define BFPagesOpportunelyWritten 236
#define BFPagesRepeatedlyWritten 238
#define BFPagesIdlyWritten 240
#define BFPageHistory 242
#define BFPageHistoryHits 244
#define BFPageHistoryReqs 246
#define BFPageScanned 248
#define BFPageScannedOutOfOrder 250
#define BFPageScannedTotal 252
#define OSFileAbnormalReadIOLatency 254
#define OSFileAbnormalWriteIOLatency 256
#define OSSLVFileTableInserts 258
#define OSSLVFileTableCleans 260
#define OSSLVFileTableDeletes 262
#define OSSLVFileTableEntries 264
#define OSSYNCThreadBlock 266
#define OSSYNCThreadsBlocked 268
#define Instances 270
#define IPagesConvertedSec 272
#define IPagesConvertedTotal 274
#define IRecordsConvertedSec 276
#define IRecordsConvertedTotal 278
#define IFCBAsyncScan 280
#define IFCBAsyncPurge 282
#define IFCBAsyncThresholdScan 284
#define IFCBAsyncThresholdPurge 286
#define IFCBAsyncPurgeConflict 288
#define IFCBSyncPurge 290
#define IFCBSyncPurgeStalls 292
#define IFCBAllocWaitForVersionCleanup 294
#define IFCBCacheHits 296
#define IFCBCacheRequests 298
#define IFCBCacheStalls 300
#define IFCBCacheMax 302
#define IFCBCachePreferred 304
#define IFCBCacheAlloc 306
#define IFCBCacheAllocAvail 308
#define IPIBInUse 310
#define IPIBUsed 312
#define IPIBTotal 314
#define ITableOpenCacheHitRate 316
#define ITableOpenCacheRequests 318
#define ITableOpenCacheHitsPerSec 320
#define ITableOpenCacheMissesPerSec 322
#define ITableOpensPerSec 324
#define ILGBytesWrittenPerSec 326
#define ILGUsersWaiting 328
#define ILGCheckpointDepth 330
#define IUserROTrxCommit0PerSec 332
#define IUserRWTrxCommit0PerSec 334
#define IUserTrxCommit0PerSec 336
#define IUserROTrxRollback0PerSec 338
#define IUserRWTrxRollback0PerSec 340
#define IUserTrxRollback0PerSec 342
#define ISystemROTrxCommit0PerSec 344
#define ISystemRWTrxCommit0PerSec 346
#define ISystemTrxCommit0PerSec 348
#define ISystemROTrxRollback0PerSec 350
#define ISystemRWTrxRollback0PerSec 352
#define ISystemTrxRollback0PerSec 354
#define IIODatabaseFileExtensionStall 356
#define ILGRecordPerSec 358
#define ILGCapacityFlushPerSec 360
#define ILGCommitFlushPerSec 362
#define ILGFlushPerSec 364
#define ILGWritePerSec 366
#define ILGStallPerSec 368
#define IVERcbucketAllocated 370
#define IVERcbucketDeleteAllocated 372
#define IVERBucketAllocWaitForVersionCleanup 374
#define IVERcbAverageBookmark 376
#define IVERUnnecessaryCalls 378
#define VERAsyncCleanupDispatched 380
#define VERSyncCleanupDispatched 382
#define VERCleanupDiscarded 384
#define VERCleanupFailed 386
#define IBTAppendSplit 388
#define IBTRightSplit 390
#define IBTVerticalSplit 392
#define IBTSplit 394
#define IBTEmptyPageMerge 396
#define IBTRightMerge 398
#define IBTPartialMerge 400
#define IBTMerge 402
#define IBTSeekShortCircuit 404
#define IBTUnnecessarySiblingLatch 406
#define IBTNext 408
#define IBTPrev 410
#define IBTSeek 412
#define IBTInsert 414
#define IBTReplace 416
#define IBTFlagDelete 418
#define IBTDelete 420
#define IBTAppend 422
#define ISPCreate 424
#define ISPCreateCum 426
#define ISPDelete 428
#define ISPDeleteCum 430
#define IBFPagesReadPerSec 432
#define IBFPagesWrittenPerSec 434
#define IBFPagesTransferredPerSec 436
#define IBFPagesPreread 438
#define IBFCachedPagesPreread 440
#define IBFPagesPrereadUntouched 442
#define IBFPagesVersioned 444
#define IBFPagesOrdinarilyWritten 446
#define IBFPagesAnomalouslyWritten 448
#define IBFPagesOpportunelyWritten 450
#define IBFPagesRepeatedlyWritten 452
#define IBFPagesIdlyWritten 454
